### ISSUE TITLE
Support?

### ISSUE THREAD

**Issue by mtorabirad** [ISI-TechknAcq/techknacq-tk#2]
Is this code being supported?

**Comment by jgordon** [comment]
No, it's research code last used four years ago. Bug fixes are welcome, but otherwise it's not being actively maintained or supported.

**Comment by mtorabirad** [comment]
@jgordon thanks for the reply. I identified and fixed a few version compatibility issues in the docker file. Let me know if you guys have any interest in adding these updates to the repo. 

I think my last hurdle is updating the https://github.com/ISI-TechKnAcq/techknacq-core/blob/master/pom.xml file. Some of the urls there are not valid anymore.

**Comment by jgordon** [comment]
Updates to the Dockerfile would be appreciated. Feel free to make a pull request whenever you like.

**Comment by mtorabirad** [comment]
@jgordon thanks again. Sure, let me fix the other issue about urls in the core and I will open a pull request.
